### ISSUE TITLE
Admin - removes duplicated i18n

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2093]
Background
==

In many sections of panel admin there is table showing the same information: **title**, **name**, **email**, **description**... 

For example, the key `Name` is repeated 20 times! 😱 

What
==

- Replace this repeated keys to something like:
```yml
admin:
  shared:
    name: "Name"
    title: "Title"
    description: "Description"
```
