### ISSUE TITLE
How to title page all.

### ISSUE THREAD

**Issue by Chanachai-Pansailom** [consul/consul#4891]
edit title web page all default. ?

**Comment by javierm** [comment]
I'm very sorry, but I'm not sure what you mean. Do you mean the title of a custom page (lin the "site content" section in the admin) or the `<title>` tag of each page? If it's the latter, check the [translations customization documentation](https://docs.consulproject.org/docs/english-documentation/customization/translations).

**Comment by johnfelipe** [comment]
@Chanachai-Pansailom 
i do this steps

STRING FROM CONSUL TO PARTICIPA-UDEA

```
nano /home/felipe/consul/config/locales/es/general.yml
##
    footer:
      accessibility: Accesibilidad
      conditions: Condiciones de uso
      consul: aplicación PARTICIPA-UDEA
      consul_url: https://
      copyright: PARTICIPA-UDEA, %{year}
      description: Este portal usa la %{consul} que es %{open_source}.
      open_source: software de código abierto
      open_source_url: http://www.gnu.org/licenses/agpl-3.0.html
      participation_text: Decide cómo debe ser la UDEA que quieres.
      participation_title: Participación
      privacy: Política de privacidad

##

nano /home/felipe/consul/config/locales/es/seeds.yml
##
      header:
        title: "PARTICIPA-UDEA"
        description: "Software libre para la participación estudiantil."
        link_text: "Más información"
        label: "Bienvenido a"

##
```

REINICIAR
sudo reboot

INICIAR LA APLICACIÓN

```
su felipe

cd consul

POSTGRES_PASSWORD=123456#789 docker-compose up -d
```
