### ISSUE TITLE
Strings not change in UI

### ISSUE THREAD

**Issue by johnfelipe** [consul/consul#4896]
```
nano /home/felipe/consul/config/locales/es/seeds.yml
##
      header:
        title: "PARTICIPA-UDEA"
        description: "Software libre para la participación estudiantil."
        link_text: "Más información"
        label: "Bienvenido a"

##

```

and still show this:
![SNAG-0086](https://user-images.githubusercontent.com/428820/182906863-e60d8d45-9bf8-4cec-9fb0-02d3c78816ed.png)

an tittle in here, view in top left side:

![SNAG-0087](https://user-images.githubusercontent.com/428820/182907046-07edfd41-d4a2-4e2d-ad23-a3d47a6fda40.png)

i reboot all ubuntu but not works
